### ISSUE TITLE
Form bugs

### ISSUE THREAD

**Issue by SSirjes** [Voog/design-zurich#22]
1. "Choose form list" settings boxes ovelap each other
   ![screen shot 2015-11-02 at 11 18 37](https://cloud.githubusercontent.com/assets/13623224/10878046/ca16fbf8-8153-11e5-9b11-7d91b3b1af00.png)
2. Form long option name is not fully readable and visible
   ![screen shot 2015-11-02 at 11 22 08](https://cloud.githubusercontent.com/assets/13623224/10878090/10284944-8154-11e5-8dd5-d6b846ba84d4.png)
3. Common page two columns: form medium and large filed width have same field width

Medium filed:
![screen shot 2015-11-02 at 11 26 28](https://cloud.githubusercontent.com/assets/13623224/10878217/dd93bc10-8154-11e5-86f5-9f06e11d96af.png)

Large field:
![screen shot 2015-11-02 at 11 26 47](https://cloud.githubusercontent.com/assets/13623224/10878225/f04b00f2-8154-11e5-98dc-a83c514caa58.png)

**Comment by otttooming** [comment]
Problem 1 seems to be common in other Voog templates and is probably not reccommended to be fixed in a template.
Problem 3 is behaviorally common to Voog standard practice of specifying form width in specific sizes, which then consolidate their visual appearance after viewport or parent container is too narrow to accomodate their visual distinctiveness. Behavior will not be changed, unless specific overriding direction is given.
