### ISSUE TITLE
Add design editor support

### ISSUE THREAD

**Issue by otttooming** [Voog/design-zurich#43]

**Comment by SSirjes** [comment]
- [x] **Main styles font don't apply to page**
  Video: http://recordit.co/rjZbSGqybc
- [x] **Front page, article title don't get main styles color values**

**kaspar-naaber:** You probably meant the front page **title** not **article title?** :)
Front page shouldn't get the color and some other styles from content page because they are too different. Front page uses the primary colors logic (like Anchorage) because it consists of bg-picker areas  while content pages are more flexible and each element can have its own color: http://recordit.co/XBiA3pEq28 (Note: there's a bug in this video – content page menu color should not be seen in front page).
- front page don't get main styles color values
  ![untitled-1](https://cloud.githubusercontent.com/assets/13623224/14783397/1645e60a-0af8-11e6-8a6f-2ffc871b367c.jpg)
- [x] article title don't get main styles color values*
  ![screen_shot_2016-04-25_at_15_08_50](https://cloud.githubusercontent.com/assets/13623224/14783434/44058e92-0af8-11e6-84cd-3b5153a09a7f.png)
- [x] **Header title preserves design-editor values after "Restore defaults"**
  Video: http://recordit.co/KoVPSqVs0i
- [x] **Submenu items have some opacity**
  If I want that submenu items would be white (#fff), then it's not possible, because submenu items have .4 opacity
  ![screen_shot_2016-04-25_at_15_44_46](https://cloud.githubusercontent.com/assets/13623224/14784147/ce1facd0-0afc-11e6-959e-cf1681fea659.png)

**Comment by SSirjes** [comment]
- [x] Form and custom button differences
  ![screen shot 2016-04-25 at 16 06 58](https://cloud.githubusercontent.com/assets/13623224/14784795/01beadb8-0b00-11e6-8602-6f5cd23abd3c.png)

**kaspar-naaber:** Because these elements are different by default, they can be modified from different places in design editor: http://recordit.co/zMlPNtPXpr

**Comment by SSirjes** [comment]
- [x] **Content options/values don't open.** Should content options be then in front page?

**kaspar-naaber:** Opening issue will be fixed from CMS side. I added some controllers to control the **Focus Area** and bottom **Content**  blocks. You can test it if it the menu toggle-ing issue is fixed.
- [x] **Form values are not correctly displayed**

![screen_shot_2016-04-25_at_22_24_34](https://cloud.githubusercontent.com/assets/13623224/14796396/bfaba738-0b35-11e6-939f-5a23adccbab2.png)

**kaspar-naaber:** Will be fixed from CMS side.

**Comment by SSirjes** [comment]
III round testing

* [ ] Header title hover difference in preview mode
Video: http://recordit.co/hULhZLPM7y
